TODO-List/config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update]
  resources :items, except: :show
end

TODO-List/app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
end

TODO-List/app/models/user.rb
class User < ActiveRecord::Base
	has_many :items
end

TODO-List/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	if cookies[:user_id]
  		user_id = cookies.signed[:user_id]
  		User.find_by_id(user_id)
  	end
  end
  helper_method :current_user  # makes method available for the views

  def sign_in user 
    if user
  	 cookies.signed[:user_id] = user.id
    end
  end

  def authenticate
  	if !signed_in?
  		redirect_to new_session_path
  	end
  end

  def signed_in?
  	current_user
  end
  helper_method :signed_in?

end

TODO-List/app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
	end
end

TODO-List/app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_filter :authenticate	

	def index
		@items = current_user.items
	end

	def new
		@item = current_user.items.new
	end

	def create
		@item = current_user.items.new(item_params)
		@item.save
		redirect_to items_path
	end

	def edit
		@item = find_item
	end

	def update
		@item = find_item
		@item.update_attributes(item_params)
		redirect_to items_path
	end

	def destroy
		@item = find_item
		@item.destroy
		redirect_to items_path
	end

	private
		def find_item
			current_user.items.find(params[:id])
		end

		def item_params
			params.require(:item).permit(:description)
		end
end

TODO-List/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_email_and_password(params[:session][:email],params[:session][:password])
		 if sign_in(user)
		 	redirect_to items_path
		 else
		 	redirect_to :back
		 end
	end

	def destroy
		cookies.delete(:user_id)
		redirect_to root_path
	end
end

TODO-List/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user.save
		sign_in @user
		redirect_to items_path
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user
		@user.update_attributes(user_params)
		redirect_to items_path
	end

	private
		def user_params
			params.require(:user).permit(:email, :password)
		end	

end

TODO-List/app/helpers/application_helper.rb
module ApplicationHelper
end

TODO-List/app/views/homes/index.html.erb
Welcome to your TODO List

TODO-List/app/views/items/edit.html.erb
<%= form_for(@item) do |form| %>
	<div>
		Item <%= form.label :description %>
		<%= form.text_field :description %>
	</div>
	<%= form.submit "Edit Item" %>
<% end %>

TODO-List/app/views/items/index.html.erb
<%= link_to "Edit Account", edit_user_path(current_user) %>
<h3>TODO List</h3>

<%= link_to "New Item", new_item_path %>

<% @items.each do |item| %>
	<div>
		• <%= item.description %>
		-
		<%= link_to "Edit", edit_item_path(item) %>
		<%= link_to "Delete", item, method: :delete, confirm: "Are you sure?"%>
	</div>
<% end %>

TODO-List/app/views/items/new.html.erb
<%= form_for(@item) do |form| %>
	<div>
		Item <%= form.label :description %>
		<%= form.text_field :description %>
	</div>
	<%= form.submit "Add Item" %>
<% end %>

TODO-List/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TODOList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div>
		<% if signed_in? %>
			Welcome <%= current_user.email %>
			<div>
				<%= link_to "Sign out", session_path, method: :delete %>
			
			</div>
		<% else %>
			<%= link_to "Sign in", new_session_path %>
			<%= link_to "Sign up", new_user_path %>
		<% end %>
	</div>

<%= yield %>

</body>
</html>

TODO-List/app/views/users/edit.html.erb
<%= form_for(@user) do |form| %>
	<div>
		<%= form.label :email %>
		<%= form.text_field :email %>
	</div>
	<div>
		<%= form.label :password %>
		<%= form.text_field :password %>
	</div>
	<%= form.submit "Edit Account" %>
<% end %>

TODO-List/app/views/users/new.html.erb
<%= form_for(@user) do |form| %>
	<div>
		<%= form.label :email %>
		<%= form.email_field :email %>
	</div>
	<div>
		<%= form.label :password %>
		<%= form.password_field :password %>
	</div>
	<%= form.submit "Sign up" %>
<% end %>